FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o bin/angel-console ./cmd/console/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/bin/angel-console .
RUN chmod +x ./angel-console
EXPOSE 3000
USER nobody
ENTRYPOINT ["./angel-console"]
