FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o bin/angel ./cmd/teamserver/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/bin/angel .
RUN chmod +x ./angel
COPY --from=builder /app/.env.example .env.example
COPY lab/certs/server.crt /app/certs/server.crt
COPY lab/certs/server.key /app/certs/server.key
RUN chmod 644 /app/certs/server.crt && chmod 644 /app/certs/server.key
EXPOSE 8443 443 53 445
USER nobody
ENTRYPOINT ["./angel"]
