FROM golang:1.27-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o bin/angel ./cmd/teamserver/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/bin/angel .
RUN chmod +x ./angel
COPY --from=builder /app/.env.example .env.example
EXPOSE 8080 8443 443 53 445
USER nobody
ENTRYPOINT ["./angel"]
